### ISSUE TITLE
Problem with unfilteredCategories

### ISSUE THREAD

**Issue by RvDstudio** [Onixaz/nextjs-woocommerce-storefront#1]
Hi i have a problem with a server error 
![image](https://user-images.githubusercontent.com/39220977/153751630-2b6d83cd-8e8c-4448-b42e-b9a3b00cfec2.png)
![image](https://user-images.githubusercontent.com/39220977/153751664-b8fcccca-2206-4a47-96c9-6bbb7a4660aa.png)
 
I hope you can help me out.
Let me know if you need more information.

**Comment by Onixaz** [comment]
Check the return value of unfilteredCategories, chances are that you're getting undefined from it, thus filter is not a function error.
